### ISSUE TITLE
Questions about expectation for the assignment

### ISSUE THREAD

**Issue by natalie-macpherson** [natalie-macpherson/dsn1676-term-project#2]
Do I absolutely need to have a introduction or some written content in my billboard? 

I have graphics, a unique idea, animations and a button but I strongly feel that for my demographic and what I am actually trying to do an introduction does not make sense in a billboard. A child would not care about an introduction they just want to see what games they can play. Don't get me wrong, there going to be written content on the page but I also want to make this engaging for a child. 

What I am propose is for the written content I have an intro. to each sections of the website instead. So for math or english I would be talking about what games or adventures a child can go on. 

What are your thoughts?

@thomasjbradley

**Comment by thomasjbradley** [comment]
That seems reasonable.
What about the title of the website?
Should there be a little tagline, “Learning games for kids.” or something?

**Comment by natalie-macpherson** [comment]
I could do that. I thought that my h1 would have been enough even though its not text but an image. Mind you, if you think about that Google I am guessing will probably ignore a <img> title. I'll take a look at it.
