### ISSUE TITLE
website on github is not the same as the website on my computer

### ISSUE THREAD

**Issue by natalie-macpherson** [natalie-macpherson/dsn1676-term-project#3]
the code for both the website and the code on my computer are exactly the same but in all of the browsers the github website is not the same. The main differences are the toggle menu and all of the typography are a lot small and browser is crossing out all of the sizes. Also the billboard is not picking up the height of the image. I am not sure what is going on or if I am explaining it right. It would be easier to show you but maybe you can help me figure it out with just looking at my html and css

@thomasjbradley

**Comment by thomasjbradley** [comment]
I don't see anything specifically. 

Could you upload some screenshots?

**Comment by natalie-macpherson** [comment]
Sorry for the delay. Busy day.

Here are my screenshots. All of the screenshots are done with the same screen size so there really should not be much of a difference.

<em>this is what it look like on a small screen for the live version</em>

![small screen live](https://cloud.githubusercontent.com/assets/6340291/6629801/723d8132-c8e8-11e4-9700-df0c832317b7.png)

<em>this is what it look like on a small screen for the one on my computer</em>
![small screen on comp](https://cloud.githubusercontent.com/assets/6340291/6629806/79a06dea-c8e8-11e4-8cf1-59247e9cbcd9.png)

<em>this is what it look like on a large screen for the live version</em>
![large screen live](https://cloud.githubusercontent.com/assets/6340291/6629810/802c0408-c8e8-11e4-96e3-1ace785f0acc.png)

<em>this is what it look like on a large screen for the lone on my compute</em>
![large screen on comp](https://cloud.githubusercontent.com/assets/6340291/6629819/8991d91e-c8e8-11e4-8667-fb15597373db.png)

Hope this helps. Also remember I might be late to the web dev I class tomorrow due to my interview.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Is the live version zoomed by the browser?
