### ISSUE TITLE
Trying smooth scrolling

### ISSUE THREAD

**Issue by natalie-macpherson** [natalie-macpherson/dsn1676-term-project#4]
I know I am jumping the gun a little bit but I was really interested in trying the smooth scrolling effect on my menu. I have input the elements into my website but it does not seem to be working. Can you take a look and help me? I have a feeling it has something to do with the js. As soon as I put in the line of script it broke the whole thing but from what I see it looks right.....

My HTML:
https://github.com/natalie-macpherson/dsn1676-term-project/blob/gh-pages/index.html#L27

My js:
https://github.com/natalie-macpherson/dsn1676-term-project/blob/gh-pages/js/main.js#L13

@thomasjbradley

**Comment by thomasjbradley** [comment]
It works on GitHub. It just doesn't work locally for you because these two lines:
https://github.com/natalie-macpherson/dsn1676-term-project/blob/gh-pages/index.html#L139-L140
Are missing `http:` at the start.

**Comment by natalie-macpherson** [comment]
oh right i forgot about that. Thank you.
